/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { MTLLoader } from 'three/examples/jsm/loaders/MTLLoader'

export function Firstamp(props) {
  const { nodes, materials } = useGLTF('/firstamp.glb')
  // const loader = useLoader(MTLLoader, )
  const test = useTexture('/alu-color.jpg')
  const alu = useTexture({
    map: '/alu-color.jpg',
    metalnessMap: '/alu-metalness.jpg',
    normalMap: 'alu-normal.jpg'
  })
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_7.geometry} receiveShadow castShadow>
        <meshStandardMaterial {...alu}/>
      </mesh>
      <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_38.geometry} material={nodes.mesh_38.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_39.geometry} receiveShadow castShadow>
        <meshStandardMaterial {...alu}/>
      </mesh>
      <mesh geometry={nodes.mesh_40.geometry} material={nodes.mesh_40.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_42.geometry} material={nodes.mesh_42.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_43.geometry} material={nodes.mesh_43.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_44.geometry} material={nodes.mesh_44.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_45.geometry} material={nodes.mesh_45.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_47.geometry} material={nodes.mesh_47.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_48.geometry} material={nodes.mesh_48.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_49.geometry} material={nodes.mesh_49.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_50.geometry} material={nodes.mesh_50.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_52.geometry} material={nodes.mesh_52.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_53.geometry} material={nodes.mesh_53.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_54.geometry} material={nodes.mesh_54.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_55.geometry} material={nodes.mesh_55.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_57.geometry} material={nodes.mesh_57.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_58.geometry} material={nodes.mesh_58.material} receiveShadow castShadow />
      <mesh geometry={nodes.mesh_59.geometry} material={nodes.mesh_59.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_60.geometry} material={nodes.mesh_60.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_62.geometry} material={nodes.mesh_62.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_63.geometry} material={nodes.mesh_63.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_64.geometry} material={nodes.mesh_64.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_65.geometry} material={nodes.mesh_65.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_67.geometry} material={nodes.mesh_67.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_68.geometry} material={nodes.mesh_68.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_69.geometry} material={nodes.mesh_69.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_70.geometry} material={nodes.mesh_70.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_71.geometry} material={nodes.mesh_71.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_72.geometry} material={nodes.mesh_72.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_73.geometry} material={nodes.mesh_73.material} receiveShadow castShadow/>
      <mesh geometry={nodes.mesh_74.geometry} material={nodes.mesh_74.material} receiveShadow castShadow/>
    </group>
  )
}

useGLTF.preload('/firstamp.glb')
